# Generated by Django 5.1.4 on 2025-01-06 10:44

import django.db.models.deletion
import house.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=house.models.GenerateHouseImagePath(),
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                ("points", models.IntegerField(default=0)),
                ("completed_tasks_count", models.IntegerField(default=0)),
                ("not_completed_tasks_count", models.IntegerField(default=0)),
                (
                    "manager",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_house",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
